name: Docker Image CI

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set lowercase repository owner
        run: |
          echo "LOWERCASE_REPO_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            dlecu/kasmweb-pycharm:1.0.1
            dlecu/kasmweb-pycharm:latest
            ghcr.io/${{ env.LOWERCASE_REPO_OWNER }}/kasmweb-pycharm:1.0.1
            ghcr.io/${{ env.LOWERCASE_REPO_OWNER }}/kasmweb-pycharm:latest 
